import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const pagePath = new URL('../src/views/exchange/record/ExchangeRecordView.vue', import.meta.url)
const routerPath = new URL('../src/router/index.ts', import.meta.url)
const layoutPath = new URL('../src/layout/AppLayout.vue', import.meta.url)
const externalSystemPath = new URL('../src/views/configuration/external-system/ExternalSystemView.vue', import.meta.url)
const batchPanelPath = new URL('../src/views/master-data/batch/components/BatchExchangeRecordPanel.vue', import.meta.url)
const tradeCatalogPath = new URL('../src/api/exchange/phisTradeCatalog.ts', import.meta.url)

test('HIS调用记录正式页面只读查询并覆盖筛选、错误和详情状态', async () => {
  const page = await readFile(pagePath, 'utf8')
  assert.match(page, /listExchangeRecords/)
  assert.match(page, /organizationCode/)
  assert.match(page, /sourceRecordId/)
  assert.match(page, /当前条件下没有调用记录/)
  assert.match(page, /<ModalFrame[^>]*labelled-by="exchange-detail-title"/)
  assert.match(page, /交易目录筛选/)
  assert.match(page, /交易码/)
  assert.match(page, /<th>请求时间<\/th>/)
  assert.match(page, /<th>接口名称<\/th><th>交易码<\/th>/)
  assert.match(page, /data-label="请求时间"/)
  assert.doesNotMatch(page, /<th>请求编号<\/th>/)
  assert.match(page, /data-label="接口名称"/)
  assert.match(page, /data-label="交易码"/)
  assert.match(page, /\.exchange-table \.prototype-tag \{ display: inline;/)
  assert.match(page, /<AdminTableFrame[^>]*label="HIS 调用记录列表"[^>]*has-actions/)
  assert.doesNotMatch(page, /HIS 调用记录只供核查|exchange-scope-note|仅展示当前账号获授权机构的数据/)
  assert.match(page, /listPhisTrades/)
  assert.match(page, /文档未收录/)
  assert.match(page, /交易目录未登记/)
  assert.doesNotMatch(page, /tradeName|医院三大目录查询|100-004.*医院三大目录查询/)
  assert.match(page, /业务关联类型/)
  assert.match(page, /同步批次/)
  assert.match(page, /外部系统端点/)
  assert.match(page, /HIS返回码（协议原值）/)
  assert.match(page, /<ListQueryToolbar class="exchange-filters" filters-layout="three-columns"/)
  const requestFrom = page.indexOf('<label class="exchange-date"><span>请求开始时间')
  const requestTo = page.indexOf('<label class="exchange-date"><span>请求结束时间')
  const resultFilter = page.indexOf('<label class="exchange-field"><span>调用结果')
  assert.ok(requestFrom >= 0 && requestTo > requestFrom && resultFilter > requestTo, '窄屏双列时开始/结束时间应连续排列，避免时间范围被拆到两行')
  assert.match(page, /\.exchange-record-page \{ display: grid; gap: 12px; container-type: inline-size; \}/)
  assert.match(page, /@container \(max-width: 1100px\)/)
  assert.match(page, /\.exchange-table tbody td:first-child \.exchange-cell-value > span,\.exchange-table tbody td:first-child \.request-code \{ overflow: visible; text-overflow: clip; white-space: normal; overflow-wrap: anywhere; \}/)
  assert.doesNotMatch(page, /exchange-filters :deep\(\.standard-list-toolbar/)
  const sharedStyles = await readFile('web-admin/src/assets/styles/prototype.css', 'utf8')
  assert.match(sharedStyles, /\.standard-list-toolbar__filters--three-columns \{ grid-template-columns: repeat\(3, minmax\(0, 1fr\)\); align-items: end; \}/)
  assert.match(sharedStyles, /@container \(max-width: 1100px\) \{\s*\.standard-list-toolbar__filters--three-columns \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); \}/)
  assert.match(sharedStyles, /@container \(max-width: 640px\) \{\s*\.standard-list-toolbar__filters--three-columns \{ grid-template-columns: minmax\(0, 1fr\); \}/)
  assert.match(page, /trade-combobox/)
  assert.match(page, /class="trade-options"/)
  assert.match(page, /@container \(max-width: 640px\)[\s\S]*?\.trade-options \{ max-height: 240px; \}/)
  assert.match(page, /@container \(min-width: 641px\) and \(max-width: 760px\)[\s\S]*?\.trade-options \{ max-height: 170px; \}/)
  assert.match(page, /filteredTrades/)
  assert.match(page, /const matchingTrades = computed\(/)
  assert.match(page, /const hasMoreFilteredTrades = computed\(\(\) => matchingTrades\.value\.length > filteredTrades\.value\.length\)/)
  assert.match(page, /v-else-if="hasMoreFilteredTrades"/)
  assert.doesNotMatch(page, /<datalist|list="phis-trade-options"/)
  assert.doesNotMatch(page, /createExchangeRecord|updateExchangeRecord|deleteExchangeRecord|runMasterDataBatch/)
})

test('交易名称和文档状态只从PhisTrade后端目录读取', async () => {
  const [page, catalog] = await Promise.all([readFile(pagePath, 'utf8'), readFile(tradeCatalogPath, 'utf8')])
  assert.match(catalog, /'\/his\/trades'/)
  assert.match(catalog, /documentedInPublicSpecification/)
  assert.match(page, /tradeFor\(record\.interfaceCode\)/)
  assert.match(page, /tradeFor\(selectedRecord\.interfaceCode\).*description/)
  assert.match(page, /isTradeCatalogUnavailable/)
  assert.doesNotMatch(page, /<input[^>]+v-model="requestId"|读取上限|最多读取条数/)
})

test('HIS调用记录具有正式路由、导航入口及调用上下文跳转', async () => {
  const [router, layout, externalSystems, batchPanel] = await Promise.all([
    readFile(routerPath, 'utf8'), readFile(layoutPath, 'utf8'), readFile(externalSystemPath, 'utf8'), readFile(batchPanelPath, 'utf8'),
  ])
  assert.match(router, /path:\s*'exchanges',[\s\S]{0,160}?component:\s*ExchangeRecordView[\s\S]{0,160}?requiredPermission:\s*'exchange:read'/)
  assert.match(layout, /to:\s*'\/exchanges',[\s\S]{0,100}?label:\s*'HIS调用记录'/)
  assert.match(externalSystems, /sourceRecordId:\s*`EXTERNAL_ENDPOINT:\$\{endpoint\.id\}`/)
  assert.match(batchPanel, /sourceRecordId: props\.sourceRecordId/)
  assert.match(batchPanel, /打开管理页/)
})
