import test from 'node:test'
import assert from 'node:assert/strict'
import { createRecoveryTasks, recoveryBlock, transitionRecovery } from '../src/views/prototype/model/recoveryWorkflow.ts'

const initial = kind => createRecoveryTasks().find(task => task.kind === kind)
const details = { assignee: '当前运维', nextCheckAt: '2026-09-15 16:00', externalOwner: '源系统李工', externalDueAt: '2026-09-16 12:00', cleanupScope: '本次请求暂存正文', linkedRequestId: 'REQ-NEW-001' }
const act = (task, action, role = 'operator') => transitionRecovery(task, action, role, 'SIM-LOG-001', '合成验证依据', task.revision, '2026-09-15 12:00:00', details)
const claim = task => act(task, 'claim')
const confirmScope = task => act(task, 'confirm-cleanup')

test('重启恢复：先检查，再回到待发送，不能伪造目标成功', () => {
  const task = initial('restart')
  assert.throws(() => act(task, 'resume'), /先检查/)
  const resumed = act(act(task, 'check'), 'resume')
  assert.equal(resumed.status, '待发送')
  assert.equal(resumed.target, '尚未发送')
  assert.equal(resumed.history.length, 2)
  assert.equal(task.history.length, 0)
  assert.throws(() => act(resumed, 'resume'), /不能恢复/)
})
test('结果未知：无法确认时不能恢复，明确未写入后仍需检查', () => {
  assert.throws(() => act(initial('unknown'), 'uncertain'), /先领取/)
  const uncertain = act(claim(initial('unknown')), 'uncertain')
  assert.equal(uncertain.status, '持续核查')
  assert.ok(recoveryBlock(uncertain, 'resume', 'operator'))
  const unwritten = act(uncertain, 'not-written')
  assert.throws(() => act(unwritten, 'resume'), /先检查/)
  assert.equal(act(act(unwritten, 'check'), 'resume').status, '待发送')
})
test('确认目标已写入后禁止覆盖或再次发送', () => {
  const written = act(claim(initial('unknown')), 'written')
  assert.equal(written.status, '已核实成功')
  for (const action of ['resume', 'written', 'not-written', 'uncertain']) assert.throws(() => act(written, action))
})
test('报告版本：交接不会覆盖原版本，也不会构造新业务成功', () => {
  const task = initial('version')
  assert.throws(() => act(task, 'resume'))
  const next = act(task, 'request-version')
  assert.equal(next.originalVersion, '1')
  assert.equal(next.latestVersion, '2')
  assert.equal(next.target, '第1版明确未写入')
  assert.equal(next.status, '等待源系统新版本')
  assert.throws(() => act(next, 'request-version'))
})
test('到期：必须停止发送才能清理，清理失败可重试，结果未知保持', () => {
  const task = initial('expiry')
  assert.throws(() => act(task, 'clean'), /先停止/)
  const stopped = act(task, 'stop')
  assert.throws(() => act(stopped, 'clean'), /确认清理范围/)
  const failed = act(confirmScope(stopped), 'clean-failed')
  assert.equal(failed.cleanupFailed, true)
  assert.throws(() => act(failed, 'resume'))
  const clean = act(failed, 'clean')
  assert.equal(clean.dataStatus, '已清理')
  assert.equal(clean.target, '无法确认')
  assert.equal(clean.cleanupFailed, false)
  const handoff = act(clean, 'handoff')
  assert.equal(handoff.status, '待核查后重新提交')
  assert.equal(handoff.target, '无法确认')
  assert.throws(() => act(handoff, 'clean'))
})
test('管理角色、跨场景动作、缺失依据和旧版本提交均拒绝', () => {
  const task = initial('restart')
  assert.throws(() => act(task, 'check', 'manager'), /只读/)
  assert.throws(() => act(task, 'clean'), /不适用/)
  assert.throws(() => transitionRecovery(task, 'check', 'operator', '', '', task.revision, 'now'), /依据/)
  const checked = act(task, 'check')
  assert.throws(() => transitionRecovery(checked, 'resume', 'operator', 'SIM-001', '依据', 0, 'now'), /已变化/)
})
test('原数据不可用或版本不同不能恢复；序列化保留状态与历史', () => {
  for (const dataStatus of ['已到期', '已清理', '清理失败']) assert.throws(() => act({ ...initial('restart'), dataStatus }, 'check'))
  assert.throws(() => act({ ...initial('restart'), latestVersion: '2' }, 'check'))
  const next = act(claim(initial('unknown')), 'written')
  assert.deepEqual(JSON.parse(JSON.stringify(next)), next)
})

test('S08：旧记录恢复后必须核查；核实成功后仍不能重发', () => {
  const restored = createRecoveryTasks().find(task => task.scenarioId === 'DESIGN-10')
  for (const action of ['check', 'resume']) assert.throws(() => act(restored, action))
  const stillUnknown = act(claim(restored), 'uncertain')
  assert.equal(stillUnknown.target, '无法确认')
  assert.throws(() => act(stillUnknown, 'resume'))
  const success = act(stillUnknown, 'written')
  assert.equal(success.status, '已核实成功')
  assert.throws(() => act(success, 'resume'))
})

test('S09：最新版本不能作为原版恢复；交接保留原请求与版本', () => {
  const unavailable = createRecoveryTasks().find(task => task.scenarioId === 'DESIGN-11')
  assert.throws(() => act(unavailable, 'resume'))
  const handed = act(unavailable, 'request-version')
  assert.equal(handed.scenarioId, unavailable.scenarioId)
  assert.equal(handed.originalVersion, '1')
  assert.equal(handed.latestVersion, '2')
  assert.equal(handed.dataStatus, '原版本不可取得')
  assert.equal(handed.target, '第1版明确未写入')
})

test('S11：发送未结束不能清理；失败后重试保持业务结果未知', () => {
  const failed = createRecoveryTasks().find(task => task.scenarioId === 'DESIGN-12')
  assert.throws(() => act({ ...failed, activeSender: true }, 'clean'), /正在发送/)
  assert.throws(() => act({ ...initial('restart'), activeSender: true }, 'check'), /正在发送/)
  const cleaned = act({ ...failed, activeSender: false }, 'clean')
  assert.equal(cleaned.dataStatus, '已清理')
  assert.equal(cleaned.target, '无法确认')
  assert.equal(cleaned.cleanupFailed, false)
  assert.throws(() => act(cleaned, 'clean'))
  assert.throws(() => act(cleaned, 'resume'))
})

test('S07：同业务号但版本不匹配，只能继续核查，不能确认成功或未写入', () => {
  const mismatch = createRecoveryTasks().find(task => task.scenarioId === 'DESIGN-13')
  for (const action of ['written', 'not-written', 'check', 'resume']) assert.throws(() => act(mismatch, action))
  const next = act(claim(mismatch), 'uncertain')
  assert.equal(next.status, '持续核查')
  assert.equal(next.originalVersion, '2')
  assert.equal(next.target, 'HIS仅确认第1版')
})

test('三条优先链路保存责任、期限、清理范围与新请求关联', () => {
  const unknown = act(claim(initial('unknown')), 'uncertain')
  assert.equal(unknown.assignee, '当前运维')
  assert.equal(unknown.nextCheckAt, details.nextCheckAt)

  const version = act(initial('version'), 'request-version')
  assert.equal(version.externalOwner, details.externalOwner)
  assert.equal(version.externalDueAt, details.externalDueAt)
  const linked = act(version, 'link-request')
  assert.equal(linked.linkedRequestId, details.linkedRequestId)
  assert.equal(linked.originalVersion, '1')

  const expiry = confirmScope(act(initial('expiry'), 'stop'))
  assert.equal(expiry.cleanupScope, details.cleanupScope)
  const handed = act(act(expiry, 'clean'), 'handoff')
  assert.equal(handed.externalOwner, details.externalOwner)
  assert.equal(handed.target, '无法确认')
})
